site_name: autodnn
repo_url: https://github.com/e0lithic/autodnn
site_url: https://e0lithic.github.io/autodnn
site_description: Automated Neural Network Compression
site_author: Arnavesh Giri
edit_uri: edit/main/docs/
repo_name: e0lithic/autodnn
copyright: Maintained by <a href="https://e0lithic.com">e0lithic</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [autodnn]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/e0lithic/autodnn
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/autodnn

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
